version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "gomod"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "github-actions"
