name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Test, Lint, and Build
    runs-on: [self-hosted, lob-runner, x64, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: make test

      - name: Lint
        uses: golangci/golangci-lint-action@v6

      - name: Build
        run: go build ./...
